spring.application.name=finance
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/EmployeeMS
spring.datasource.username=postgres
spring.datasource.password=Lavanya
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Properties for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
